### ISSUE TITLE
ImportError: cannot import name 'LightningDataset' from 'torch_geometric.data'

### ISSUE THREAD

**Issue by zhi520** [cvignac/MiDi#2]
MiDi/midi_src/datasets/adaptive_loader.py", line 6, in <module>
    from torch_geometric.data import LightningDataset

ImportError: cannot import name 'LightningDataset' from 'torch_geometric.data'

**Comment by cvignac** [comment]
It's probably related to your pytorch_geometric version, can you check it using `pip list`?

Clement

**Comment by liguanglin** [comment]
Hi, I found that the LightningDataset moved to [torch_geometric.data.lightning.LightningDataset](https://github.com/pyg-team/pytorch_geometric/tree/master/torch_geometric/data/lightning). Maybe you could try this.

**Comment by cvignac** [comment]
Thank you, I have fixed the code accordingly.
