### ISSUE TITLE
There is no dataset called qm0 and no experiment call qm9_no_h in your files

### ISSUE THREAD

**Issue by Longwei-Yang** [cvignac/MiDi#9]
```
python3 main.py dataset=qm0 dataset.remove_h=True +experiment=qm9_no_h
```

This line is not even runnable. There is no dataset called qm0 and no experiment called qm9_no_h.

There are some typos I guess.

**Comment by cvignac** [comment]
Fixed. I don't appreciate at all the first edition of your comment, it wasn't even remotely polite.

**Comment by Longwei-Yang** [comment]
I do apologize for it. Setting up the environment made me feel annoyed and impatient sometime.
Hope you have a good day.
